name: Docker

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: argocd-plugin-helmfile

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and push image
        run: |
          IMAGE_WITH_TAG=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{github.ref_name}}
          IMAGE_LATEST=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
          docker buildx build --push --platform linux/amd64,linux/arm64/v8 --tag $IMAGE_WITH_TAG --tag $IMAGE_LATEST .
